# Generated by Django 4.0.4 on 2022-06-05 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='employed',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='studying',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.DateField(default=datetime.date(2022, 6, 6)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default='', help_text='Enter a question', max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduate_year',
            field=models.DateField(default=datetime.date(2022, 6, 6)),
        ),
    ]
