# Generated by Django 4.0.4 on 2022-05-19 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asking', '0003_book_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('pk_faculty', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['-faculty_name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('pk_group', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=30)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asking.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('pk_institute', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('institute_name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['-institute_name'],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('pk_mailing', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mailing_date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('a', 'Active'), ('i', 'Inactive')], default='i', max_length=1)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asking.institute')),
            ],
            options={
                'ordering': ['-mailing_date'],
            },
        ),
        migrations.CreateModel(
            name='MailingResult',
            fields=[
                ('pk_mailing_result', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asking.mailing')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('pk_question', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular question', primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='Enter a question', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMailing',
            fields=[
                ('pk_question_mailing', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asking.mailing')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asking.question')),
            ],
            options={
                'ordering': ['-question'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('pk_result', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('graduate_number', models.IntegerField()),
                ('answer_number', models.IntegerField()),
                ('causes', models.IntegerField()),
                ('coefficient', models.FloatField()),
                ('employed', models.IntegerField()),
                ('graduate_year', models.DateField()),
            ],
            options={
                'ordering': ['pk_result'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('pk_student', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('status', models.CharField(blank=True, choices=[('s', 'Study'), ('g', 'Graduate')], default='s', max_length=1)),
                ('mail', models.CharField(max_length=50)),
                ('graduate_year', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asking.group')),
            ],
            options={
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='language',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='mailingresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asking.result'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asking.institute'),
        ),
    ]
